app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:memo_id>', views.detail, name='detail'),
    path('new_memo', views.new_memo, name='new_memo'),
    path('delete_memo/<int:memo_id>', views.delete_memo, name='delete_memo'),
    path('edit_memo/<int:memo_id>', views.edit_memo, name='edit_memo'),
]

memo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

class Memo(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

app/forms.py
from django.forms import ModelForm
from .models import Memo

class MemoForm(ModelForm):
    class Meta:
        model = Memo
        fields = ['title', 'text']

app/views.py
from django.shortcuts import render, redirect
from .models import Memo
from django.shortcuts import get_object_or_404
from .forms import MemoForm
from django.views.decorators.http import require_POST

def index(request):
    memos = Memo.objects.all().order_by('-updated_datetime')
    return render(request, 'app/index.html', { 'memos': memos })

def detail(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    return render(request, 'app/detail.html', { 'memo': memo })

def new_memo(request):
    if request.method == "POST":
        form = MemoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:
        form = MemoForm
    return render(request, 'app/new_memo.html', {'form': form})

@require_POST
def delete_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    memo.delete()
    return redirect('app:index')

def edit_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    if request.method == "POST":
        form = MempForm(request.POST, instance=memo)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:
        form = MemoForm(instance=memo)
    return render(request, 'app/edit_memo.html', {'form': form, 'memo': memo})

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoBrosMemo</title>
</head>
<body>
    <h1>DjangoBrosMemo</h1>

    <div class="contaoner">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

app/templates/app/detail.html
{% extends 'app/base.html' %}

{% block content %}

    <div>
        <a href="{% url 'app:index' %}">ホームに戻る</a>
    </div>

    <h2>{{ memo.title }}</h2>
    <div>
        {{ memo.text | linebreaks | urlize }}
    </div>

    <button><a class="btn" href="{% url 'app:edit_memo' memo.pk %}">編集</a></button>

    <form method="POST" action="{% url 'app:delete_memo' memo.pk %}">{% csrf_token %}
        <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？")'>削除</button>
    </form>

{% endblock %}

app/templates/app/edit_memo.html
{% extends 'app/base.html' %}

{% block content %}

    <div>
        <a href="{% url 'app:detail' memo.id %}">戻る</a>
    </div>

    <form action="{% url 'app:edit_memo' memo.id %}" method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn" type="submit">保存</button>
    </form>

{% endblock %}

app/templates/app/index.html
{%  extends 'app/base.html' %}

{% block content %}

    <a class="btn" href="{% url 'app:new_memo' %}">新規メモ作成</a>

    {% for memo in memos %}
    <a href="{% url 'app:detail' memo.id %}" class="memo-title">
        <div>
            {{ memo }}
            <span class="updated_datetime">{{ memo.updated_datetime }}</span>
        </div>
    </a>
    {% endfor %}

{%  endblock %}

app/templates/app/new_memo.html
{% extends 'app/base.html' %}

{% block content %}

    <div>
        <a href="{% url 'app:index' %}">ホームに戻る</a>
    </div>

    <form action="{% url 'app:new_memo' %}" method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">保存</button>
    </form>

{% endblock %}